services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/db:/data/db
  server:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MONGO_URL
      - SESSION_SECRET
      - PORT
    command: npm run dev
    ports:
      - 3000:${PORT}
    depends_on:
      - mongodb