services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/db:/data/db
  server:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./:/app
      - ./${UPLOAD_FOLDER}:/app/${UPLOAD_FOLDER}
    environment:
      - MONGO_URL
      - SESSION_SECRET
      - PORT
      - UPLOAD_FOLDER
      - CORS_ORIGIN
    command: npm run dev
    ports:
      - ${DOCKER_PORT}:${PORT}
    depends_on:
      - mongodb