services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/db:/data/db
  server:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./:/app
      - ./${UPLOAD_FOLDER}:/app/${UPLOAD_FOLDER}
    environment:
      - MONGO_URL=mongodb://mongodb/${MONGO_DB_NAME}
      - SESSION_SECRET
      - PORT
      - UPLOAD_FOLDER
    command: npm run dev
    ports:
      - 3000:${PORT}
    depends_on:
      - mongodb